### ISSUE TITLE
Chroma shift

### ISSUE THREAD

**Issue by flossy83** [Asd-g/AviSynthPlus-NNEDI3CL#10]
Hello

I noticed on both my 1070 and R9380 the chroma is shifted upward slightly by a small amount compared to `nnedi3_rpow2`.

Animated PNG of `nnedi3_rpow2(rfactor=4, nns=1, nsize=0)` vs `2xNNEDI3CL(field=1, nns=1, nsize=0, dh=true, dw=true)`
![animated](https://user-images.githubusercontent.com/46382337/222486414-039b509c-17cf-4362-abae-5849501d3340.png)

Also the entire image is shifted upwards by about 1px (I corrected that in photoshop for the animated png above) - maybe that has something to do with it?  Maybe the thing which is shifting the image upwards is mishandling the chroma as part of that movement upwards?   Or maybe it's just a GPU driver issue that is beyond your control?

Full frames:
[nnedi3_rpow2(rfactor=4, nns=1, nsize=0)]( https://i2.lensdump.com/i/TqPbEe.png)
[2xNNEDI3CL(field=1, nns=1, nsize=0, dh=true, dw=true)](https://i.lensdump.com/i/TqPG31.png) 

Of course we can correct it manually ourselves with `MergeChroma` , so it's not a huge deal.

Thanks

**Comment by Asd-g** [comment]
Yes, it's expected. You can create your own wrapper fixing it. You can also use [nnedi3wrap](https://github.com/Dogway/Avisynth-Scripts/issues/61).

**Comment by flossy83** [comment]
Thanks.

It seems the entire image shift changes depending on the size of images handled... not sure how to get a consistent result myself.

This is problematic if I'm doing something like `bwdif(edeint=NNEDI3CL())` , because the alignment will be off for interpolated pixels. 

Would it be easy to copy the source code from nnedi3(cshift=)?
https://github.com/jpsdr/NNEDI3/blob/master/nnedi3/nnedi3.cpp#L4382

**Comment by Asd-g** [comment]
Chroma shift will occur if `dh`/`dw` true. In your example `bwdif(edeint=NNEDI3CL())` there shouldn't be chroma shift.

`nnedi3` doesn't have `cshift` parameter but `nnedi3_rpow2` has such parameter.

**Comment by flossy83** [comment]
Sorry I didn't explain my situation well enough.

For a 720x480i source I'm trying to use `NNEDI3CL(dw,dh).NNEDI3CL(dw,dh)` on each 720x240 field as the basis for my interpolated pixels when deinterlacing.  I think I can get higher quality interpolated pixels this way with the optimal `nsize` setting, compared to just "take a frame, throw away one field, and then interpolate the missing pixels using only information from the remaining field", as we normally get with `NNEDI3CL()` or `nnedi3()`.  

`nnedi3_rpow2(4)` is too slow for realtime use.  `NNEDI3CL(dw,dh).NNEDI3CL(dw,dh)` is fast enough for realtime use, but doesn't support the cshift parameter like `nnedi3_rpow2(4, cshift="bicubicresize")`, so I need to manually implement the cshift myself which seems complex and I don't understand it well enough to get the alignment correct for all size video files.

Chroma shift is actually only a small problem, the bigger problem is that the entire image center is shifted so the interpolated pixels won't even line up properly when deinterlacing with eg. `bwdif(edeint=my_4x_nnedi3_clip_supersampled_down_to_480p)`

**Comment by Asd-g** [comment]
Try the added [script](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/blob/main/NNEDI3CL_rpow2.avsi).

**Comment by flossy83** [comment]
Seems to be working...  image shift is same as nnedi3_rpow2 and chroma position is retained:

[nnedi3_rpow2(rfactor=4, nns=1, nsize=0, cshift="BicubicResize")](https://i1.lensdump.com/i/TmRcnD.png)
[NNEDI3CL_rpow2(rfactor=4, nns=1, nsize=0, cshift="Bicubic")](https://i2.lensdump.com/i/TmRX5q.png)

Much appreciated, thank you.
