### ISSUE TITLE
Black screen with prefetch / 16 bit

### ISSUE THREAD

**Issue by tormento** [Asd-g/AviSynthPlus-NNEDI3CL#12]
I want to rescale an anime (source=BD) using:

```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Madogatari ~BDJP\madogatari.dgi")
Convertbits(16)
libplacebo_Resample(1280,720,filter="lanczos")
nnedi3CL_rpow2(rfactor=4, nsize=0, nns=4, qual=2, etype=0)
libplacebo_Resample(1920,1080,filter="lanczos")
libplacebo_Deband(iterations=2,temporal=true)
fmtc_bitdepth (bits=10,dmode=7)
Prefetch(2)
```

but it shows a black screen unless I correct it as

```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Madogatari ~BDJP\madogatari.dgi")
libplacebo_Resample(1280,720,filter="lanczos")
nnedi3CL_rpow2(rfactor=4, nsize=0, nns=4, qual=2, etype=0)
libplacebo_Resample(1920,1080,filter="lanczos")
libplacebo_Deband(iterations=2,temporal=true)
Prefetch(2)
```

The following works too

```
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Madogatari ~BDJP\madogatari.dgi")
Convertbits(16)
libplacebo_Resample(1280,720,filter="lanczos")
nnedi3CL_rpow2(rfactor=4, nsize=0, nns=4, qual=2, etype=0)
libplacebo_Resample(1920,1080,filter="lanczos")
libplacebo_Deband(iterations=2,temporal=true)
fmtc_bitdepth (bits=10,dmode=7)
```

Any idea why?

**Comment by Asd-g** [comment]
Try with `nnedi3CL_rpow2(rfactor=4, nsize=0, nns=4, qual=2, etype=0, st=true)`.

**Comment by tormento** [comment]
Nope, it doesn't work.

In addition, when I preview with VirtualDub2, I get:

![image](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/assets/2351785/4040271b-c1b6-45c1-8521-351c7cbe9b17)

With AvsPmod, I get:

![image](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/assets/2351785/5655a0cc-416e-4445-a2e3-7087eb148523)

**Comment by Asd-g** [comment]
Another two tests:
- if you replace `DGSource("M:\In\Madogatari ~BDJP\madogatari.dgi")` with `ColorBars(1920, 1080, pixel_type="yv12")`?
- try this:
```
source
Convertbits(16)
libplacebo_Resample(1280,720,filter="lanczos")
Prefetch(2)
nnedi3CL_rpow2(rfactor=4, nsize=0, nns=4, qual=2, etype=0)
Prefetch(1, 0)
libplacebo_Resample(1920,1080,filter="lanczos")
libplacebo_Deband(iterations=2,temporal=true)
fmtc_bitdepth (bits=10,dmode=7)
Prefetch(2)
```

**Comment by tormento** [comment]
Again:

![image](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/assets/2351785/6eb5b33b-12b9-4b6f-bd50-9af5c78efe56)

**Comment by Asd-g** [comment]
Which one of the both two tests or both of them give the error? You can try to update the GPU drivers if not the latest are used.

Edit: I cannot reproduce the issue that's why asking for these test.

**Comment by tormento** [comment]
Both. My drivers are the latest from nVidia. I have tried insider ones too.

If there is something I can do to help you more, tell me.

**Comment by tormento** [comment]
I've just found that
```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\The dangers in my heart ~763p BDJP\1\11.dgi")
Convertbits(16)
libplacebo_Resample(1358,764,filter="ewa_lanczossharp")
nnedi3CL_rpow2(rfactor=2, nsize=6, nns=4, qual=2, etype=0)
Edgelevel(strength=10,bc=10)
libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")
libplacebo_Deband(iterations=3,temporal=true)
fmtc_bitdepth (bits=10,dmode=7)
Prefetch(2)
```
works but
```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\The dangers in my heart ~763p BDJP\1\11.dgi")
Convertbits(16)
libplacebo_Resample(1358,764,filter="ewa_lanczossharp")
nnedi3CL_rpow2(rfactor=2, nsize=6, nns=4, qual=2, etype=0)
libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")
Edgelevel(strength=10,bc=10)
libplacebo_Deband(iterations=3,temporal=true)
fmtc_bitdepth (bits=10,dmode=7)
Prefetch(2)
```
doesn't. That's funny.

Notice the inversion of lines 8-9.

**Comment by Asd-g** [comment]
Thanks for the tests. It seems `libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")` doesn't release the GPU instance.

Try the following:

```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\The dangers in my heart ~763p BDJP\1\11.dgi")
Convertbits(16)
Prefetch(2)
libplacebo_Resample(1358,764,filter="ewa_lanczossharp")
Prefetch(2)
nnedi3CL_rpow2(rfactor=2, nsize=6, nns=4, qual=2, etype=0)
Prefetch(1)
libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")
Prefetch(2)
Edgelevel(strength=10,bc=10)
Prefetch(1)
libplacebo_Deband(iterations=3,temporal=true)
Prefetch(2)
fmtc_bitdepth (bits=10,dmode=7)
Prefetch(2)
```

**Comment by tormento** [comment]
That works but it's a mess with all those prefetch calls. :)

Any idea about how to fix the issue?

**Comment by Asd-g** [comment]
Try the attached test version of avs_libplacebo.

[avs_libplacebo.zip](https://github.com/Asd-g/AviSynthPlus-NNEDI3CL/files/15048968/avs_libplacebo.zip)

**Comment by Asd-g** [comment]
ping @tormento

**Comment by tormento** [comment]
@Asd-g sorry, my bad.

If you look at the first script, you will notice `rfactor=4` and that's probably the error reason.

I have a 1660 Super with 6GB of VRAM and, perhaps, a 4x resize falls beyond that boundary.

Regarding the post about the swap of the lines
```
libplacebo_Resample(1358,764,filter="ewa_lanczossharp")
nnedi3CL_rpow2(rfactor=2, nsize=6, nns=4, qual=2, etype=0)
Edgelevel(strength=10,bc=10)
libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")
```
to 
```
libplacebo_Resample(1358,764,filter="ewa_lanczossharp")
nnedi3CL_rpow2(rfactor=2, nsize=6, nns=4, qual=2, etype=0)
libplacebo_Resample(1920,1080,filter="ewa_lanczossharp")
Edgelevel(strength=10,bc=10)
```
they both works now, even with the release avslibplacebo version, BUT I have updated the frame server to Avisynth+ 3.7.3·4073.

As curiosity, what did you change with the test version?

**Comment by Asd-g** [comment]
No worries. I pinged in case you noticed the comment but forgot to reply.

The test version has some kind of GPU instances tracking.
