### ISSUE TITLE
field order not working for dh=true

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynthPlus-NNEDI3CL#2]
As I was replacing nnedi3 with NNEDI3CL I found an issue (I think) that can be triggered with the next code:

```
SeparateFields()
SelectOdd()
ExtractY()
# nnedi3(dh=true,nsize=3,nns=3,qual=2)
NNEDI3CL(1,dh=true,nsize=3,nns=3,qual=2) # 1 or 0 yields same filling order
```

**Comment by Asd-g** [comment]
It seems you have frame property `_FieldBased` > 0 before the NNEDI3CL call. In such case the `field` option is set according to the value of `_FieldBased` (`_FieldBased`=1 => field=0 and `_FieldBased`=2  => field=1). 
You can delete `_FieldBased` (or set it to 0) to have the same behavior as nnedi3.

**Comment by Dogway** [comment]
Thanks! That did the trick.
