### ISSUE TITLE
How to use NNEDI3CL?

### ISSUE THREAD

**Issue by SangenBR** [Asd-g/AviSynthPlus-NNEDI3CL#5]
whenever I call NNEDI3CL() it gives this error image below
![w](https://user-images.githubusercontent.com/42396360/188294519-6c336ae8-beb2-4f85-a78a-d9f2784f2565.png)

**Comment by Asd-g** [comment]
`NNEDI3CL(clip input, int field, bool "dh", bool "dw", int[] "planes", int "nsize", int "nns", int "qual", int "etype", int "pscrn", int "device", bool "list_device", bool "info", bool "st")`

`int field` - field is without quotes meaning it must be specified. For example you can use `NNEDI3CL(1)`.

**Comment by Reel-Deal** [comment]
There's also examples in the wiki: http://avisynth.nl/index.php/NNEDI3CL#Examples

**Comment by SangenBR** [comment]
It worked, thx.
