### ISSUE TITLE
EEDI3CL port?

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/AviSynthPlus-NNEDI3CL#7]
Hi Asd, 

Would you consider porting [EEDI3CL ](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3)to AVS+? I know that EEDI3 is not as widely used as NNEDI3 but it still has it uses and the original EEDI3 plugin is still limited to 8-bit.

**Comment by Asd-g** [comment]
Hi,
I will port it but no eta.

**Comment by Reel-Deal** [comment]
Hi, 

No worries, I understand that time is a limited resource. Thanks for considering it.

**Comment by kedaitinh12** [comment]
Can you backport both eedi3 and eedi3cl? Cause in some case cl ver don't faster than eedi3 and eedi3 avisynth cpu ver don't support HBD

**Comment by Asd-g** [comment]
I could port the CPU version in case @pinterf doesn't have plans to add support for high bit depth.

**Comment by kedaitinh12** [comment]
> I could port the CPU version in case @pinterf doesn't have plans to add support for high bit depth.

He don't have plans cause he don't have time
https://forum.doom9.org/showthread.php?p=1929654#post1929654

**Comment by pinterf** [comment]
Yes, I've got no further plans with the plugin.

**Comment by Asd-g** [comment]
EEDI3CL - https://github.com/Asd-g/AviSynthPlus-EEDI3CL

**Comment by kedaitinh12** [comment]
You only ported EEDI3CL??

**Comment by Asd-g** [comment]
Yes, for now.

**Comment by kedaitinh12** [comment]
Ok, thanks

**Comment by Reel-Deal** [comment]
> EEDI3CL - https://github.com/Asd-g/AviSynthPlus-EEDI3CL

Thanks Asd! I will test it out in the next couple of days
