### ISSUE TITLE
Support alpha processing?

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/AviSynthPlus-NNEDI3CL#8]
Hi Asd,

I noticed that NNEDI3CL does not handle the alpha plane properly. There is no error when the source has an alpha, but the output is just black.
```
src = ColorBars(pixel_type="RGBP8").Trim(1,1)
msk = Blankclip(src, color=0).Subtitle("MASK BE GONE", align=5, size=72, text_color=$FFFFFF, halo_color=0).ExtractR()
AddAlphaPlane(src,msk)
NNEDI3CL(1, dh=true, dw=true, planes=[0,1,2,3])

Interleave(msk.BicubicResize(width, height), last.ExtractA())
```

NNEDI3 works correctly with this script.

Edit: even with planes=[0,1,2,3] it does not do anything.

**Comment by Asd-g** [comment]
Hi,

please try 1.0.5.

**Comment by Reel-Deal** [comment]
Just tested it and work as it should. I'll update the wiki to mention that if you want to also process the alpha plane in an RGBA/YUVA source, planes must be set to [0,1,2,3]. Thanks for the quick fix.

Edit: forget the last part, did not see you had made [0,1,2,3] the default.
